// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Card is the predicate function for card builders.
type Card func(*sql.Selector)

// Order is the predicate function for order builders.
type Order func(*sql.Selector)

// Product is the predicate function for product builders.
type Product func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
